version: 2
jobs:
  build:
    docker:
    - image: python:3
    steps:
    - checkout
    - run:
        name: Setup testing environment
        command: |
          pip install --default-timeout=1000 --no-cache-dir -r requirements.txt
    - run:
        name: run tests
        command: |
          mkdir test-results
          pytest --verbose --no-header --junit-xml=test-results/junit.xml
    - store_test_results:
        path: test-results/junit.xml
    - store_artifacts:
        path: test-results
    - run:
        name: Run coverage
        command: |
          coverage run -m pytest
          coverage report
          coverage html
    - store_artifacts:
        path: htmlcov
    - run:
        name: run linting and metrics
        command: |
          mkdir linter-reports
          flake8 ./cli.py --format=pylint  --output-file linter-reports/linter.txt
    - store_artifacts:
        path: linter-reports    
workflows:
  version: 2
  workflow:
    jobs:
    - build