version: 2
jobs:
  tests:
    docker:
    - image: python:3 #Docker image and version which will be used during tests
    steps:
    - checkout
    - run:
        name: Setup testing environment #Install required test packages
        command: |
          pip install --default-timeout=1000 --no-cache-dir -r requirements.txt
    - run:
        name: Run PyTests #Export junit report to test-results folder
        command: |
          mkdir test-results
          pytest --verbose --no-header --junit-xml=test-results/junit.xml
    - store_test_results:
        path: test-results/junit.xml #Upload report to CircleCI Insights
    - store_artifacts:
        path: test-results #Save report as a build artifact
    - run:
        name: Run coverage #Run codecoverage and export report. Don't break anything!
        command: |
          coverage run -m pytest
          coverage report
          coverage html
    - store_artifacts:
        path: htmlcov #Save report folder as build artifact
    - run:
        name: run linting and metrics #Run linter and export report. Don't break anything!
        command: |
          mkdir linter-reports
          flake8 -vv ./cli.py --format=pylint  --output-file linter-reports/linter.txt || cat linter-reports/linter.txt && echo "Yes, I know my mistakes, please don't break :("
    - store_artifacts:
        path: linter-reports #Save report folder as build artifact   
  deploy:
    machine: true #Use VM instead of container to run docker commands
    steps:
      - checkout
      - run: 
          name: Login to DockerHub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      # build the application image
      - run: 
          name: Build Application Image
          command: |
            docker build -t cnsn/marvel:latest. 
      # deploy the image
      - run:
          name: Deploy Application Image #Container image security and vulnerability tests could be added..
          command: |
            docker push cnsn/marvel:latest

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - tests
    - deploy: #Deployment requires tests to be successfull
        requires: 
          - tests 