version: 2
jobs:
  build:
    docker:
    - image: python:3
    steps:
    - checkout
    - run:
        name: Setup testing environment
        command: |
          pip install --default-timeout=1000 --no-cache-dir -r requirements.txt
    - run:
        name: Run pytest
        command: |
          pytest cli_test.py --junitxml=pytest-results/report.xml
    - store_test_results:
      path: pytest-results
    - run:
        name: Run coverage
        command: |
          coverage run -m pytest
          coverage report
          coverage html
    - store_artifacts:
        path: htmlcov
    
workflows:
  version: 2
  workflow:
    jobs:
    - build