version: 2
jobs:
  build:
    docker:
    - image: python:3
    steps:
    - checkout
    - run:
        name: Setup testing environment
        command: |
          pip install --default-timeout=1000 --no-cache-dir -r requirements.txt
    - run:
        name: run tests
        command: |
          mkdir test-results
          pytest --verbose --cov-report html:~/test-results/coverage_html --cov=. --junitxml=~/test-results/junit.xml
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results
#    - run:
#        name: Run coverage
#        command: |
#          coverage run -m pytest
#          coverage report
#          coverage html
#    - store_artifacts:
#        path: htmlcov
    
workflows:
  version: 2
  workflow:
    jobs:
    - build