version: 2
jobs:
  build:
    docker:
    - image: python:3
    steps:
    - checkout
    - run:
        name: Setup testing environment
        command: |
          pip install --default-timeout=1000 --no-cache-dir -r requirements.txt
    - run:
        name: Run pytest
        command: |
          pytest -q cli_test.py
    - run:
        name: Run coverage
        command: |
          $HOME/.local/bin/coverage run -m pytest
          $HOME/.local/bin/coverage report
          $HOME/.local/bin/coverage html
    - store_artifacts:
        path: htmlcov
workflows:
  version: 2
  workflow:
    jobs:
    - build